#! /bin/bash

if [ $UID -eq 0 ] 
then
    apt-get -y install doxygen
    apt-get -y install libxrandr-dev
    apt-get -y install libxcursor-dev
    apt-get -y install libxi-dev
    apt-get -y install libxext-dev
    apt-get -y install libxinerama-dev
else 
    echo "Must be run as root"
fi
