name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
         sudo apt-get install doxygen
         sudo apt-get install libxrandr-dev
         sudo apt-get install libxinerama-dev
         sudo apt-get install libxcursor-dev

    - name: Build
      run: cmake . && make
